# Build configure for https://www.tea-ci.org (fork of Drone CI with Msys2 support)
# 32-bit until release including https://sourceware.org/git/gitweb.cgi?p=newlib-cygwin.git;a=commitdiff;h=0aa738220bb9dea2ad479e484560767b36701947
build:
  image: teaci/msys32
  shell: mingw32
  pull: true
  branches:
    -master
  environment:
    - SUBTARGET=tiny
    - MINGW32=/c/msys32/mingw32
    - MAME_EXE=tiny.exe
#    - SOURCES=src/mame/drivers/pacman.cpp
  commands:
    - make
    - ./$MAME_EXE -validate || echo "Validation successful"
  
# Need to create secrets file from within tea-ci.org
#notify:
#  email:
#    from: git@mamedev.org
#    host: $$EMAIL_SERVER
#    username: $$EMAIL_USERNAME
#    password: $$EMAIL_PASSWORD
#    recipients:
#      - $$EMAIL_LISTADDR
#    when:
#      success: false
#      failure: false
#      change: true
